version: '3.8'

services:
  postgres_users:
    container_name: postgres_users
    image: postgres:16
    environment:
      POSTGRES_USER: parma
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: param
    ports:
      - "5433:5432"
    networks:
      - ecommerce-network
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
      - './init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql'
volumes:
  postgres_data:
networks:
  ecommerce-network:
    driver: bridge